.gitignore, selendroid-standalone/src/test/java/io/selendroid/standalone/android/impl/AbstractDeviceTest.java
The old regex failed to match [/android-sdk-macosx/platform-tools/adb, shell, ps]
=> Fix testListThirdPartyProcesses

lib/commands/actions.js, lib/commands/element.js, lib/commands/find.js, lib/commands/general.js, lib/driver.js, lib/uiautomator2.js
- Added drag, tap and click
- Handled webview support, added exclusive `CHROME_NO_PROXY` list and also implemented `suspendChromedriverProxy` . 
- Added `killUiAutomatorOnDevice`  to kill the existing the running server instance if any on device.
- Added `wrapBootstrapDisconnect` to support network actions.
=> Added Webview support, tap, click, drag functions and wrapBootstrapDisconnect for network actions

lib/uiautomator2.js
Hello.
I had issue that whenever I run test on multiple device separately(different test script), one of my devices which ran in first uiautomator2 has been killed.
Here is my setting.
appium version : 1.6.2 using uiautomator2
test environment : two devices attached on one PC, two appium server running on two different port
I noticed that below command sent to all my devices. 
`2016-12-06 14:28:24:842 - info: [UiAutomator2] running command...
adb shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner... 
2016-12-06 14:28:24:843 - info: [UiAutomator2] running command...
adb shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner... `
I am not sure about the purpose of send command to all …
=> uiautomator2 multiple deivce issue

package.json
`portscanner` 1.1.0 is deprecated. In an effort to minimize the production install warnings, upgrade (the breaking change in `portscanner` is also in 1.1.0, which is why it is deprecated).
=> Upgrade portscanner package

lib/driver.js
When executing driver.removeApp (bundleId), the following error occurs.
```
[HTTP] --> POST /wd/hub/session/d8621726-4bb6-49fe-9c9c-536868af1f4e/appium/device/remove_app {"bundleId":"xxxxxxxxxxxxxxxxxxxxxxxx"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/d8621726-4bb6-49fe-9c9c-536868af1f4e/appium/device/remove_app] to [POST http://localhost:8200/wd/hub/session/cfbf5cdf-9c69-4722-aebf-04d202c542d8/appium/device/remove_app] with body: {"bundleId":"xxxxxxxxxxxxxxxxxxxxxxxx"}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:342:13)
at tryCatch …
```
=> Fix fail "driver.removeApp(bundleId)"

lib/driver.js
The below document says if `reboot` option is true, reboot emulator after each session and kill it at the end.
https://github.com/appium/appium/blob/v1.6.3/docs/en/writing-running-appium/server-args.md
But actually it works only when using appium-android-driver.
So I implemented the reboot option with reference to the implementation of appium-android-driver.
=> Implement reboot option

lib/desired-caps.js, lib/driver.js
This will allow driver successful initialization even when the device screen remains locked.
=> Added skipUnlock

lib/driver.js, test/functional/commands/keyboard/keyboard-e2e-specs.js
Save the IME that is in use before switching to Appium's Unicode keyboard. Analogous to https://github.com/appium/appium-android-driver/blob/master/lib/driver.js#L224
Fixes https://github.com/appium/appium/issues/8755
=> Save default IME so we can restore

lib/driver.js, lib/server.js, test/functional/commands/url-e2e-specs.js, test/functional/desired.js
* Call 'startChromeSession' on chrome sessions
* Refactor URL tests to use 'wd' instead of internal commands
(connected to: https://github.com/appium/appium-uiautomator2-driver/pull/92)
=> Use chromedriver for Chrome sessions

lib/desired-caps.js, lib/driver.js, lib/uiautomator2.js, test/functional/desired.js
New cap `disableWindowAnimation` which disables animations (using `--no-window-animation` flag) on instrumentation process.
See https://github.com/appium/appium/issues/5400
=> Add cap to stop animations on instrumentation

lib/driver.js, package-lock.json, package.json, test/functional/commands/general-e2e-specs.js, test/functional/commands/language-e2e-specs.js, test/functional/commands/strings-e2e-specs.js, test/functional/helpers/helpers.js
The driver has the ability to get the strings from the device, so don't proxy the request. This seems to fix https://github.com/appium/appium/issues/8930, though setting the locale/language is flakey so the tests are quarantined in Travis.
=> Do not proxy getting app strings

lib/driver.js
`/log/types` endpoint implemented in `appium-android-driver` and should not  be proxied to `appium-uiautomator2-server`.
=> Add `/log/types` endpoint to NO_PROXY

lib/driver.js
When I run tests fully in `ruby_lib` against `uiautomator2`, `v0.7.0` driver, I found some commands we should set no-proxy.
The following is an example of `install_app`.
```
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/c98fdf58-4ec8-43e6-8676-6b2eba2b97c4/appium/device/install_app] to [POST http://localhost:8200/wd/hub/session/dde9b411-1457-4795-86a0-c6fbe046a1b7/appium/device/install_app] with body: {"appPath":"/Users/kazucocoa/GitHub/ruby_lib/test_apps/api.apk"}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
at doJwpProxy$ (/Users/kazucocoa/GitHub/appium/node_modules/appium-base-driver/lib/mjsonwp/m …
```
=> add some commands we should set as no-proxy

lib/driver.js, package.json, test/functional/commands/keyboard/keyboard-e2e-specs.js
I saw several issue reports about UIA2 is not working properly and then it turns out that people are trying to run it on Android 4.4 or even older versions. This PR should improve the situation.
=> Throw an exception if running on an unsupported OS

lib/desired-caps.js
This is needed to prevent "unknown capability" error from base driver.
=> Add systemPort to the list of desired caps

lib/driver.js, test/functional/commands/mobile-command-e2e-specs.js
When I tied to run `mobile: shell` against uiautomator2 with Ruby client, the following error raised.
After adding them to `NO_PROXY`, the mobile command works well.
```
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while pr
ocessing the command. Original error: Could not proxy. Proxy error: Could not proxy comm
and to remote server. Original error: 404 - undefined
```
Also, I've added the execute command for W3C since I haven't seen this kind of commit.
link: https://github.com/appium/appium-android-driver/pull/293
---
- I'll add one `mobile: shell` command test
```
dbug ADB Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","--remove","tcp:8200"]
dbug BaseDriver Event …
```
=> add execute script to no proxy

lib/driver.js, test/unit/driver-specs.js
**Issue:**
nativeWebScreenshot preference was overwritten on each getProxyAvoidList call. This makes screenshot command getting proxied to chromedriver when user is on webview mode. Which most likely will timeout.
**Implementation:**
Fix test cases to actually check proxyAvoidList content by feeding in `/session/zzz/screenshoot/`.
Former test for nativeWebScreenshot had false positive since NO_PROXY list is already over 40 items.
Add additional test cases to specify native mode behavior which ignores nativeWebScreenshot setting.
=> getProxyAvoidList should not overwrite additional rule

lib/driver.js, lib/uiautomator2.js
This change is needed if we are running tests on a device connected to the remote machine. 
1)JWProxy uses  :server instead of :host
2) tell adbkit about remoteAdbHost instead of assuming localhost. This fixes starting instrumentation on remote machine with 'adb shell am instrument..'
=> fix JWProxy opt key. Also pass adb host to adbkit

lib/commands/general.js, lib/driver.js, test/unit/commands/general-specs.js
https://github.com/appium/appium-xcuitest-driver/pull/607 for uiautomator2.
```
[debug] [MJSONWP] Responding to client with driver.getWindowRect() result: {"height":1794,"width":1080,"x":0,"y":0}
[HTTP] <-- GET /wd/hub/session/c8a361e8-9d63-4535-aba7-6d4931ceada7/window/rect 200 37 ms - 50
[HTTP] --> GET /wd/hub/session/c8a361e8-9d63-4535-aba7-6d4931ceada7/window/rect {}
[debug] [MJSONWP] Calling AppiumDriver.getWindowRect() with args: ["c8a361e8-9d63-4535-aba7-6d4931ceada7"]
[debug] [JSONWP Proxy] Proxying [GET /window/current/size] to [GET http://localhost:8208/wd/hub/session/836468f0-151b-44ae-950c-f7b9ade9ae08/window/current/size] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"836468f0-151b-44ae-950c-f7b9ade9ae08\",\"status\":0,\"value\":{\"height\ …
```
=> Window rect for w3c

lib/driver.js
Fix the following proxy error for `terminate_app` and `activate_app`
```
[HTTP] --> POST /wd/hub/session/c579c9fc-32cc-49b8-9dc5-3ad46c4fe80f/appium/device/terminate_app {"appId":"io.appium.android.apis"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/c579c9fc-32cc-49b8-9dc5-3ad46c4fe80f/appium/device/terminate_app] to [POST http://localhost:8200/wd/hub/session/328f5c81-65c3-41dd-9c8b-ad819dbf29fc/appium/device/terminate_app] with body: {"appId":"io.appium.android.apis"}
[W3C] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
at doJwpProxy$ (/Users/kazuaki/GitHub/appium/node_modules/appium-base-driver/lib/protocol/proto …
```
=> fix proxy error for activate and terminate app

lib/driver.js, test/unit/commands/touch-specs.js
Unlocking the device depends on an API which requires a session ID.
startUiAutomator2Session needs to start the session before trying to unlock the device.
=> Unlock the device after the session has been started

test/functional/commands/find/by-uiautomator-e2e-specs.js
Note: with this changes all UiScrollable tests will fail - as it should be, due to issue appium/appium#9328.
=> UiScrollable tests should perform fair scrolling - not a single swipe.

lib/driver.js, package.json
* Now that we use `apkAnalyzer` to parse activity names, it's not always going to be the case that an activity name will be "fully qualified"
* We need to set retry to `true` again so that if the activity does not have '.' in front of it, try again with the dot
* e.g.: If running activity `io.appium.android.apis/ApiDemos` does not work, make it try again with `io.appium.android.apis/.ApiDemos`
(related to https://github.com/appium/appium-adb/pull/308)
(connected to issue https://github.com/appium/appium/issues/10381)
=> Add retry to startApp method call

lib/commands/general.js, package.json, test/functional/commands/general/mobile-command-e2e-specs.js
* Use `mobile: deepLink` as the command name
* Requires a URL and Package
* Will only work if instant apps are enabled on the device/emulator, otherwise it throws an exception
(connected to: https://github.com/appium/appium/issues/10329)
=> Add deep link command

lib/driver.js
`createSession` return the desired capabilities.
According to JSON Wire Protocol that `createSession` should return the actual session's capabilities.
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#post-session
=> createSession should return session's capabilities

lib/driver.js
The call to this endpoint simply freezes otherwise
=> Add compare_images to the list of NO_PROXY endpoints

lib/commands/battery.js, lib/commands/general.js, lib/commands/index.js, package.json, test/functional/commands/general/mobile-command-e2e-specs.js
Based on https://github.com/appium/appium-uiautomator2-server/pull/143
=> Add a possibility to retrieve battery info from real devices

lib/driver.js, test/functional/commands/general/context-e2e-specs.js, test/functional/driver-e2e-specs.js
We were having a default webview name of `WEBVIEW_0`, which never exists anymore. So use the same method as the `appium-android-driver`. This addresses https://github.com/appium/appium/issues/10784
Also fix the build, which has been failing on the adb port tests.
=> Fix handling of autoWebview

lib/commands/general.js, lib/commands/viewport.js, lib/driver.js
As @mykola-mokhnach rightly pointed out, these memoizations need to happen on instances, rather than on the prototype.
=> Per-instance memoization

lib/commands/general.js, lib/driver.js, package.json
The original android-bootstrap component needs resource strings to be available as json on the destination device in order to "fix" element lookups. UIA2 server does not apply any fixes there, so there is no need to extract and upload strings json on session init. This change also allows to save a great amount of time. 
I'm going to delete the `/wd/hub/session/:sessionId/appium/app/strings` handler from UIA2 server, since it is a dummy implementation, which has absolutely no effect.
=> Fix strings extraction

lib/driver.js
As mentioned in https://github.com/appium/appium/pull/11640#issuecomment-438260477 , `--no-window-animation` doesn't disable animation duration correctly. It disables only window and transtion animation. Over Android8, it works correctly though.
Let me consider https://github.com/appium/appium-android-driver/pull/464 and https://github.com/appium/appium-espresso-driver as well a bit.
=> fix disabling animation

lib/driver.js
Removed killing any existing UIAutomator2 processes running on device
during phase of UIAutomator2Server initialization, which is not required
at that point, due to possibility of re-installation apks. 
Processes are killed either way on the begging of session startup in function startSession in uiautomator2.js and I can't see the point in doing it twice.
=> Removed redundat UIAutomator processes killi during UIAutomator initialization

lib/driver.js
Fixed startup for web execution. Currently chrome browser is started
twice: firstly by ensureAppStarts and then by startChromeSession. 
I think it can be simplified and done similarly to solution implemented in
AndroidDriver.
=> Fixed duplicated chrome startup

lib/desired-caps.js, lib/driver.js, lib/uiautomator2.js
New capability 'skipServerInstallation' is introduced in
order to allow user to skip UIAutomator2Server installation phase.
The installation and validation of currently installed versions can be
omitted if user is sure that applications in proper versions are already installed.
It allows for huge performance improvement (even about 50% in some cases).
=> Implement capability to skip server installation

lib/uiautomator2.js
We'd like to re-install UIA2 server if installed UIA2 is not equal to running Appium server's UIA2.
In our use case, below case can happen.
- A user can use arbitrary Appium version
- test devices are in shared pool
Then,
1. User A uses Appium 1.10.0 on device X
2. User B uses Appium 1.11.0 on device X
3. User A uses Appium 1.10.0 on device X again
- then, device X has a UIA2 bundled in Appium 1.11.0. Current logic does not downgrade the UIA2 on device X to the one bundled in Appium 1.10.0 since the UIA2 bundled in 1.11.0 is not `OLDER_VERSION_INSTALLED`. (The appium version is an example)
- In this case, we would like to use UIA2 bundled in 1.10.0
We can skip installation phase only when UIA2 server on test device is the same as UIA2 Appium would like to use.
What do you think? …
=> add re-installing a uia2 server when the newer version of uia2 server is on test device

lib/uiautomator2.js, test/unit/uiautomator2-specs.js
Tests for making sure install/uninstall logic depends on `getApplicationInstallState`
Related to: https://github.com/appium/appium-uiautomator2-driver/pull/270
=> Add tests for install/uninstall following the result of getApplicationInstallState

lib/uiautomator2.js
We cannot rely on the exit code which is returned to the host, so I switched the logic to verify the original exit code received directly from adb shell. Thanks to @KazuCocoa for pointing that out
=> Improve am service pinging logic

lib/uiautomator2.js
It seems like there is no good way to healthcheck am service state. Let's just rely on the delay between instruments startup retries.
https://github.com/appium/appium-uiautomator2-driver/pull/281#issuecomment-456671943
=> Remove am service state verification

lib/desired-caps.js
This desired cap is in our docs and code, but was missing from the validation. Just cleaning up :)
=> add androidCoverageEndIntent to desiredCapConstraints

lib/uiautomator2.js
It looks like the instrumentation process is not very talkative on some phone models.
Addresses https://discuss.appium.io/t/appium-1-11-0beta3-take-to-long-to-initialize-the-app/25166
=> Hardcode instrumentation wind up time interval

lib/driver.js
Only espresso driver calls disabling/enabling animation before `this.initAUT();`
UIA2 can also follow it
=> move disabling animation before autoLaunch check

lib/driver.js, lib/helpers.js, lib/uiautomator2.js
I see users are confused by standard signer errors, which are happening because of missing FS permissions. This PR adds a separate verification of the fact that the destination file is writeable prior to sign it and raises a proper error message.
=> Verify file system permissions before signing files

lib/driver.js
The current `No open port found` error message is not very helpful.
=> Add a better error message if no free port is found

.travis.yml, package.json, test/functional/helpers/mocha-scripts.js, test/functional/helpers/session.js
We have been letting the `mocha-scripts.js` code get loaded implicitly, which has begun to fail.
=> Fix handling of server start

lib/uiautomator2.js, test/unit/uiautomator2-specs.js
I faced the below case. Then, I must uninstall SERVER_PACKAGE_ID by manual to fix the issue. Without the uninstallation, never Appium becomes health.
- SERVER_TEST_PACKAGE_ID is not in a test device
- SERVER_PACKAGE_ID is in the test device
- and SAME_VERSION_INSTALLED
Thus, I would like to enable `shouldInstallServerPackages` if the test device has no `test` package.
This case is not so common. So, I just enable it instead of separate the logic for SERVER_TEST_PACKAGE_ID and SERVER_PACKAGE_ID.
=> fix no only test package case

lib/uiautomator2.js, package.json
This PR adds an additional step, which verifies if there are any obsolete sessions running on the device  and sends the DELETE command to them in order to properly shutdown UIA2 server process before starting a new one.
@KazuCocoa Can you please try your magic scenario with "double" session creation with this PR?
=> Improve session leftovers cleanup

lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/514/files
=> Add permissions handling mobile endpoints

lib/driver.js
Add code from `appium-android-driver` to support the `gpsEnabled` desired capability.
=> Add handling of gpsEnabled cap

test/functional/commands/find/by-uiautomator-e2e-specs.js
People have been reporting problems with `fromParent` in UiAutomator searches (e.g., https://github.com/appium/appium-uiautomator2-server/issues/282). Add a test so we can demonstrate it working.
=> Add test for UiSelector.fromParent

lib/desired-caps.js, lib/driver.js, test/functional/commands/general/mobile-command-e2e-specs.js
Closes https://github.com/appium/appium/issues/12962
appium-adb already has an option, `waitForLaunch`, to remove `-W` for instrument command.
`waitForLaunch` is true by default.
This PR add the ability for UIA2.
- With `appWaitForLaunch`
```
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -n io.appium.android.apis/io.appium.android.apis.ApiDemos -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
```
- Without `appWaitForLaunch` (or true)
```
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.android.apis/io.appium.android.apis.ApiDemos -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f …
```
=> feat: add a capability of waitForLaunch

lib/helpers.js
Related to https://github.com/appium/appium-desktop/issues/1115
=> fix: Tune write access verification on Windows

lib/driver.js, package.json
Currently I observe the situation that when two parallel sessions are executed at the same time then the `findAPortNotInUse` method returns the same available port for both sessions since none of them hasn't allocated this port yet.
=> fix: Add locking mechanism for dynamic system port allocation algorithm

lib/commands/general.js, lib/driver.js, package.json
This is the part of https://github.com/appium/appium/issues/13466 implementation
=> feat: Get clipboard content via ADB if necessary on Android 10

lib/driver.js
Related to appium/appium#13663, seemed like uiautomator2 never passed in waitDuration to appium-adb. waitActivity always uses the default value. If i'm wrong, please ignore this PR.
What types of changes does your code introduce to Appium?
=> Pass waitDuration to adb startApp

lib/driver.js, package.json
The signing operation takes time and could also create issues if one wants to upgrade the app under test, because it is impossible to perform reinstall if the previously installed app version has been signed with the different signature.
=> fix: Do not require the default signature if the app under test is already signed

ci-jobs/scripts/start-emulator.sh
Azure's MacOS environment has HAXM installed. Plus, if set to `auto` it will just ignore it if not available.
=> build: use acceleration in azure emus

lib/desired-caps.js, lib/driver.js, lib/uiautomator2.js, package.json, test/unit/driver-specs.js, test/unit/uiautomator2-specs.js
Depends on https://github.com/appium/appium-uiautomator2-server/pull/289
```
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","--no-window-animation","-e DISABLE_SUPPRESS_ACCESSIBILITY_SERVICES true","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
```
is the output of with `disableSuppressAccessibilityService: true` capability.
I tested with breakpoint to run with/without `disableSuppressAccessibilityService` with https://github.com/appium/appium-uiautomator2-server/pull/289
=> feat: add disableSuppressAccessibilityService

lib/commands/general.js, package.json
Added condition to handle waitForLaunch capability to call concerned startUrl function.
Which will fix below issue.
https://github.com/appium/appium/issues/14180
It's depends on below PR
https://github.com/appium/appium-adb/pull/520
=> feat: Add an option to control intent wait for a started URI

lib/driver.js
Two reasons: 
1. It matches the log level further down where you reset the API Policy to the default: 
```js
if (await this.adb.getApiLevel() >= 28) { // Android P
logger.info('Restoring hidden api policy to the device default configuration');
await this.adb.setDefaultHiddenApiPolicy();
}
```
2. It's not really a warning if it's always set and not something we can actually fix/remediate.
Plus, it shows up in our console logs, which are warning only and it's noisy: 
See https://github.com/appium/appium-uiautomator2-driver/pull/242#discussion_r430560813 for original discussion.
=> fix: Change API Policy log level from warn to info

lib/uiautomator2.js, package.json
Based on https://github.com/appium/appium-adb/pull/535
=> fix: Always install server binaries with incremental option disabled

lib/commands/general.js
In order to be able to locate native elements correctly, one must be able to tell the viewport rectangle, in addition to getting the viewport screenshot. That's because native elements return with locations relative to the device, not the viewport.
So now, once we have a native element's coordinates, we can subtract the viewport's origin coordinate and the result will be the native element's coordinates relative to the viewport.
=> feat: Expose ViewPortRect mobile command.

ci-jobs/pr-validation.yml, ci-jobs/templates/android-e2e-template.yml, lib/driver.js, package.json
If a process has been forcefully terminated then a file lock might be left in an undefined state. This PR adds an option to it, which tries to recover the lock from this state. Also, it reduces the timeout to 25 seconds, because the default adb command timeout is anyway 20 seconds.
Related to https://github.com/appium/appium/issues/14682
=> fix: Tune port guard lock options

lib/uiautomator2.js
The previous behavior made the client to wait until timeout happens (240 seconds by default) if the server stops responding. This fix will make the code to throw an error immediately without waiting for a response and also provide more helpful exception message
=> feat: Throw an immediate exception if instrumentation process is dead

lib/driver.js
https://discuss.appium.io/t/the-uiautomator2-driver-keeps-recording-the-screen-even-though-the-session-has-deleted/32885
=> fix: Make sure screen recording stops after a session is closed

lib/driver.js
iOS does app install, but does not launch it, which makes more sense in the capability name context.
=> fix: Align autoLaunch capability behaviour with iOS

README.md, lib/commands/gestures.js
This is needed because selenium API does unexpected transformations of argument key names. See https://github.com/appium/appium/issues/15392#issuecomment-844355078 for more details
=> chore: Deprecate element argument in favour of elementId in `mobile: scroll` extension

lib/uiautomator2.js
The property name is /sessions API output is `sessionId` rather than `id`
=> fix: Update properly name in session cleanup

lib/commands/general.js
This is basically what https://github.com/appium/appium-uiautomator2-driver/pull/499 is supposed to do, just quite simplified in order to fix the original issue ASAP.
=> fix: Update the way driver settings are updated

package.json
So far, our each driver release includes `shrinkwrap` to specify dependencies.
https://github.com/appium/appium-uiautomator2-driver/blob/master/.github/workflows/publish.js.yml
It needs to push a new version when we'd like to include dependencies's update like https://github.com/appium/appium-android-driver/pull/732
(This PR change itself does not need, but it needs to kick a release task)
=> fix: Read package name from web view info if not provided explicitly by updating android driver

lib/commands/touch.js
* ActionChains in selenium have a PointerInput whose kind(pointerType) is "mouse".
* We should change this to "touch" for android devices to work properly.
* (I confired "mouse" doesn't work and "touch" works.)
* There is code for converting "mouse" to "touch" ("preprocessedActions")
* But wrong old variable was used.
----
I try again with email corresponding GitHub because EasyCLA is not working
=> fix: wrong parameter in performActions

README.md, package.json
Maybe it would be nice to bump the minor version up since activateApp behaves a bit differently for API level 24.
=> feat: activateApp calls "am start" for over api level 24 devices

package.json
Closes https://github.com/appium/appium/issues/17679
=> chore: bump UIA2 server to use non-android.permission.WRITE_EXTERNAL_STORAGE one

lib/driver.js, lib/method-map.js, package.json
depends on https://github.com/appium/appium-android-driver/pull/782
=> fix: specify supported non-standard commands in newMethodMap

.github/workflows/functional-test.yml, package.json, test/functional/commands/file-movement-e2e-specs.js, test/functional/commands/geo-location-e2e-specs.js, test/functional/commands/language-e2e-specs.js, test/functional/commands/orientation-e2e-specs.js, test/functional/commands/strings-e2e-specs.js, test/functional/commands/viewport-e2e-specs.js
I just started looking into https://github.com/appium/appium/issues/16402
This PR aims for spec files directly under `test/functional/commands` dir. Subdirectories are not included.
I confirmed `npm run e2e-test:commands` passed on my laptop with `android-30;google_apis;arm64-v8a` emulator.
I have a question, what is `process.env.TESTOBJECT_E2E_TESTS` for? Do you still use it?
=> ci: fix and enable some commands e2e specs

lib/commands/element.js, lib/driver.js, test/functional/commands/general/ime-e2e-specs.js, test/functional/commands/keyboard/keyboard-e2e-specs.js
it seems like actually the capability is no longer needed for UIA2 driver. I was able to send unicode with without them, double checked.
=> chore: remove unused unicodeKeyboard as uia2

package.json
It seems like https://github.com/appium/appium-chromedriver/pull/289 ? broke the chromedriver version comparison, which was fixed in https://github.com/appium/appium-chromedriver/pull/291 . It caused https://github.com/appium/appium/issues/18368
=> fix: chromedriver version comparison in the chromedriver downloading

README.md
New argument uploadTimeout added to mobile: stopMediaProjectionRecording documentation.
For: https://github.com/appium/appium/issues/18549
=> docs: add mobile: stopMediaProjectionRecording uploadTimeout

.github/workflows/functional-test.yml, test/functional/commands/general/attribute-e2e-specs.js, test/functional/commands/orientation-e2e-specs.js
I noticed functional test for api-25 always fails on the some specific test cases
e.g.
https://github.com/appium/appium-uiautomator2-driver/actions/runs/4752045785/jobs/8441915286?pr=597
https://github.com/appium/appium-uiautomator2-driver/actions/runs/4744576967/jobs/8425670890?pr=596
https://github.com/appium/appium-uiautomator2-driver/actions/runs/4729447613/jobs/8391973545
https://github.com/appium/appium-uiautomator2-driver/actions/runs/4608686473/jobs/8144798439
I can't reproduce it on my laptop then it'd take time to investigate.
Could we just skip them for now?
=> ci: skip some find element test cases for api-25 as they are flaky

README.md
I got a question about `enforceAppInstall` with noReset capability. It would be helpful to explain the relationship in the readme briefly.
=> docs: address noReset in the enforceAppInstall

README.md
I was somewhat confused about `mjpegServerPort` being listed twice in the docs. Turns out one applies to the host machine, and the other to the remote device. This PR aims to help clarify this (as well as some mentions of other ports).
For consistency it would of course be better if the host machine capability was called `mjpegSystemPort`, similarly to `systemPort`, but that would certainly be a breaking change.
I've also included a small fix for a broken link to the old Appium docs.
=> docs: clarify host vs remote ports, fix Appium docs link

lib/driver.js
This adds logging for the port forwarding done as part of an MJPEG broadcasting request. Similar to the log message for forwarding the UiAutomator2 server port in `allocateSystemPort()`.
=> chore: add logging for mjpeg broadcast request

README.md, docs/android-mobile-gestures.md, docs/scheduled-actions.md, package.json
Based on https://github.com/appium/appium-uiautomator2-server/pull/510
=> feat: Add extensions for scheduled actions

.github/workflows/functional-test.yml, lib/uiautomator2.js, test/functional/helpers/session.js, test/unit/uiautomator2-specs.js
It makes sense to perform some server installation actions in parallel to save some time on session startup.
The change should also make the current code more readable
=> refactor: Optimize server packages installation

.github/workflows/functional-test.yml, scripts/run-functional-tests.sh
Several tests are flaky because of the CI slowness. I've added a threshold value of 10% to still pass the suite in case of failure (currently allows 3 tests out of 30 to fail)
=> ci: Add a threshold for functional test pass

mkdocs.yml, package.json, typedoc.json
This adds basic documentation generation via `appium-docs`. 
Future work should include: 
- Add the human-written docs to the nav in `mkdocs.yml`
- More descriptions of commands (in docstrings)
- Some sort of landing page or otherwise fix the broken links in the generated `README.md`
- Add a workflow to build and/or publish docs
To build & serve:
```bash
npm exec appium-docs build -- --serve
```
=> chore: add basic doc gen

lib/desired-caps.js
UIA2 driver can start sessions without app being set
=> chore: Disable app capability presence validation

lib/uiautomator2.js
I observed weird behavior on an Android 13 Samsung device. This was only a specific device so far but potentially could happen on other devices. (I mean I cannot say this does not happen on other devices)
What I saw was in a new session request from uia2 driver to the uia2 server. These are in `createSession` in `driver.js`.
- `/wd/hub/session` create session -> ok 200
- `/wd/hub/session/0e62d0be-bfb4-403e-8b85-6af9ae40fbfd/appium/device/info` -> ok
- `/wd/hub/session/0e62d0be-bfb4-403e-8b85-6af9ae40fbfd/appium/device/pixel_ratio` -> invalid session id for `0e62d0be-bfb4-403e-8b85-6af9ae40fbfd`
According to the adb log cat, it seems like the uia2 server process stop in `cleanupAutomationLeftovers`? probably delayed. So activity stop log actually existed before `/wd/hub/session` in the …
=> fix: check if the instrumentation process stops by sending a request

lib/driver.ts
Tune the error message to give more hints for users
=> chore: tune error messages for setHiddenApiPolicy 

README.md
* Update Java `executeScript` code example to use `Map.ofEntries` instead of `Map.of`
* It is important to use `Map.ofEntries`, because `Map.of` is limited to 10 key-value pairs, and some extension methods support more than 10 parameters, e.g. `mobile: startActivity`
* Remove code example for `mobile: performEditorAction`, since now there are common examples at the start of the extensions section
=> docs: update Java executeScript example

README.md
`appium:skipLogCapture` should be `appium:skipLogcatCapture` as far as I tried as below
```
[AppiumDriver@e4ea] Appium v2.2.2 creating new AndroidUiautomator2Driver (v2.29.11) session
[AppiumDriver@e4ea] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[AppiumDriver@e4ea] Appium's BaseDriver version is 9.4.2
[AppiumDriver@e4ea] AndroidUiautomator2Driver's BaseDriver version is 9.4.2
[AndroidUiautomator2Driver@9dde] Creating session with W3C capabilities: {
[AndroidUiautomator2Driver@9dde]   "alwaysMatch": {
[AndroidUiautomator2Driver@9dde]     "platformName": "android",
[AndroidUiautomator2Driver@9dde]     "appium:app": "/Users/mwakizaka/Documents/10_projects/apps/MobileWebViewApps/webview_app_debug.apk",
[AndroidUiautomator2Driver@9dde]     "appium:deviceName": …
```
=> docs: fix wrong capability name and some typos

package.json
to include
https://github.com/appium/appium-uiautomator2-server/pull/583
https://github.com/appium/appium-uiautomator2-server/pull/585
explicitly.
=> feat: bump the server's targetSdkVersion from 32 to 33

README.md, lib/execute-method-map.ts, package.json
Based on https://github.com/appium/appium-android-driver/pull/896
=> feat: Document the helper method to simulate the low-memory event

package.json
=> fix: bump appium android driver to 7.8.3 (for getContexts)

lib/commands/screenshot.js
It seems that `mobile: screenshots` does not work in the Inspector (which is based on WDIO):
```
[AndroidUiautomator2Driver@2eaa (71335d72)] Calling AppiumDriver.execute() with args: ["mobile: screenshots",[],"71335d72-7790-446c-8fe0-ed7e7f070a3c"]
[AndroidUiautomator2Driver@2eaa (71335d72)] Executing method 'mobile: screenshots'
[ADB] Running '/Users/alvaro/Library/Android/sdk/platform-tools/adb -P 5037 -s <udid> shell dumpsys SurfaceFlinger --display-id'
[AndroidUiautomator2Driver@2eaa (71335d72)] Parsed Android display infos: {"4619827677550801152":{"id":"4619827677550801152","isDefault":true,"name":"Common Panel"}}
[AndroidUiautomator2Driver@2eaa (71335d72)] Encountered internal error running command: Error: The provided display identifier 'undefined' is not known. Only the following …
```
=> fix: fix `mobile: screenshots` for WDIO

README.md, lib/execute-method-map.ts, package.json
https://github.com/appium/appium-android-driver/pull/915 for uia2.
I noticed missing args about `mobile: removeApp` in the readme, so this pr includes it as well.
=> feat: add checkVersion option for mobile:installApp

README.md
Just spent a whole day trying to make use of the "mobile: getNotifications" script. 
Maybe it is just me, but it wasn't obvious that there might be multiple Settings where notification permissions can be set, depending on the vendor. I was having no trouble making use of this feature in a Samsung device but I wasn't able to it in a Xiaomi Poco F3. Eventually, I [figured out](https://github.com/appium/io.appium.settings/issues/147) that there was a Special Permissions section, at the Privacy menu, where I could give yet more Notification permissions.
This MR is just an effort to try and raise awareness about that and hopefully make life easier for other people who come across the same issue.
Let me know if this PR seems useful or can be improved in any way.
Best regards o/
=> docs: getNotification improvement

package.json
No issue was observed in https://github.com/appium/appium-uiautomator2-server/pull/615 for now, so I think we can bump the server version as chore. (not feat level).
Closes https://github.com/appium/appium/issues/19597
I'll merge this after CI check passes
=> chore: bump uia2 server that has androidx.test.uiautomator:uiautomator:2.3.0

docs/uiautomator-uiselector.md
Updated links to the UiAutomator documentation.
Also it seems that the UiSelector and UiScrollable classes [will be deprecated in the future](https://developer.android.com/training/testing/other-components/ui-automator#ui-automator), so it may be worth considering adding support for UiObject2/BySelector.
=> docs: update UiAutomator reference links

README.md
Fixed typo in Android driver name 'uiautomator2' in doctor command
=> docs: appium doctor driver command typo

lib/uiautomator2.js
It's actually only taking time since we always preresign server packages automatically upon package release.
=> chore: Skip signature checks of server packages

README.md, package.json
Based on https://github.com/appium/appium-android-driver/pull/930
=> feat: Add the support of `timeZone` capability

.github/workflows/functional-test.yml
Just curious about Ubuntu and Enable KVM group perms
https://github.blog/changelog/2024-04-02-github-actions-hardware-accelerated-android-virtualization-now-available/
https://github.com/reactivecircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners
https://github.com/appium/appium-uiautomator2-driver/actions/runs/8012939666
Maybe this is the most recent succeeded cases:
=> ci: Enable KVM group perms

README.md
Unlike espresso driver, uia2's animation can be restored after the installation process ends in api level 26+. It might be helpful to explain the fact in the doc as well.
=> docs: address restoring animation scale

package.json
To use api level 32 built settings apk
=> chore: use latest io.appium.settings

package.json
to create a version with https://github.com/appium/appium-android-driver/pull/939
I'll merge after CI passes
=> fix: Add a workaround for wrong adb exit code on service stop

lib/uiautomator2.js, test/unit/uiautomator2-specs.js
https://github.com/appium/appium/issues/19799#issuecomment-2181932720
The current UIA2 driver does not uninstall UIA2 servers on the device if they are newer than newly installed servers by the UIA2. It could cause old UIA2 driver with newer UIA2 servers on the device, which is a mismatch condition. It could cause unexpected behavior.
 
Maybe... `this.adb.APP_INSTALL_STATE.NOT_INSTALLED` condition should be `this.adb.APP_INSTALL_STATE.NEWER_VERSION_INSTALLED` to "uninstall" installed UIA2 servers?
It looks like `sinon` mock's `expects`, `never`, once etc might not be so reliable. Some could be not good. To improve condition check as test code, I have extracted condition check into two methods and added tests for them. At least `shouldUninstallServerPackages` and `canInstallServerPackages` …
=> fix: uninstall installed uia2 servers if they were greater than on-going session

README.md, lib/commands/clipboard.js, lib/commands/execute.js, lib/commands/misc.js, lib/commands/types.ts, lib/driver.ts
"Built-in" clipboard APIs have been [deprecated](https://github.com/appium/appium/blob/cc10b65ee53b2da8bc7845eacbe3b1583eacb712/packages/base-driver/lib/protocol/routes.js#L860), so we need to provide proper mobile wrappers for getting and setting clipboard content in drivers where it is supported.
=> feat: Add mobile: wrappers for clipboard APIs

lib/uiautomator2.js
More tuning fix for https://github.com/appium/appium-uiautomator2-driver/pull/655 
I observed that to ensure that the `/status` endpoint stops, we should kill the `io.appium.uiautomator2.server` process as well in addition to `io.appium.uiautomator2.server.test`. Only `.test` process kill keep responding to the `/status`. So as `cleanupAutomationLeftovers`, it would be reasonable to stop both processes
(this behavior finding is an edge case in my another issue investigation though)
=> fix: stop io.appium.uiautomator2.server process as well (in cleanupAutomationLeftovers)

README.md
for https://github.com/appium/appium/issues/20730#issuecomment-2463928490
=> docs: add example for startActivity

scripts/run-functional-tests.sh
* The current script has a lot of undocumented dependencies.
* By checking for them explicitly, developers don't need to read cryptic test failures, to understand what they are missing.
=> ci: Check local setup before running functional tests

README.md, lib/commands/types.ts, package.json
`pkg` parameter of `startUri()` becomes optional from appium-adb 12.7.3 by https://github.com/appium/appium-adb/pull/776.
This PR follows this change by making `package` parameter of `mobileDeepLink()` optional.
=> fix: Make package parameter of deep link command optional

docs/bidi.md, package.json
Same as https://github.com/appium/appium-xcuitest-driver/pull/2503
Based on https://github.com/appium/appium-android-driver/pull/973
=> chore: Tune contextUpdated event generation

lib/driver.ts, package.json
Based on https://github.com/appium/appium-android-driver/pull/975
=> fix: Tune retrieval of package launch info

README.md
I was trying to run a custom driver locally and noticed the commands were not up-to-date: `npm run watch` didn't work and neither did the e2e-test command
- `npm run dev` seems to be the new short for `npm run build -- --watch`
- I didn't find a single command to run all flavors of e2e-tests so I listed all of them
=> test: update README Development commands

lib/commands/app-management.js, lib/driver.ts, lib/execute-method-map.ts, package.json
https://github.com/appium/appium-android-driver/pull/988
I'll merge after CI gets green
=> chore: remove duplicated mobile: backgroundApp definition from uia2

.github/workflows/functional-test.yml
To run with the latest Beta
The test execution speed seems similar to the existing API level 28, so I think it makes sense to enable API level 36 for upcoming Android 16 testing as well.
=> ci: run with Android 16 also

README.md
- Fixed a typo in the README: “webcoket listener” → “websocket listener”
- Corrected the documented WebSocket endpoint for logcat broadcasting:  
`/ws/session/:sessionId:/appium/logcat` → `/ws/session/:sessionId:/appium/device/logcat`
- The new path reflects the actual behavior of Appium as observed in runtime logs.
> Did not match the websocket upgrade request at  
> `/ws/session/<sessionId>/appium/logcat` to any known route
> [AndroidUiautomator2Driver] Starting logcat broadcasting on web socket server  
> `{"address":"0.0.0.0","family":"IPv4","port":4723}`  
> to `/ws/session/8f8b8d76-53c0-4ca9-87ef-4a1281e3e4fc/appium/device/logcat`
=> docs: fix endpoint for "mobile: startLogsBroadcast"
