.gitignore, android-driver/AndroidManifest.xml, android-driver/build.gradle, build.gradle, pom.xml, selendroid-client/build.gradle, selendroid-common/build.gradle, selendroid-grid-plugin/build.gradle, selendroid-server-common/build.gradle, selendroid-server/AndroidManifest.xml, selendroid-server/build.gradle, selendroid-server/src/main/java/io/selendroid/server/model/SelendroidWebDriver.java, selendroid-standalone/build.gradle, selendroid-standalone/src/test/java/io/selendroid/standalone/android/impl/AbstractDeviceTest.java, selendroid-test-app/build.gradle, selendroid-test-app/res/layout/webview.xml, selendroid-test-app/src/main/java/io/selendroid/testapp/WebViewActivity.java, selendroid-test-app/src/test/java/io/selendroid/webviewdrivertests/WebElementInteractionTest.java, settings.gradle
As Selendroid makes changes upstream, it's good to periodically rebase so we don't fall too far behind.
> git pull --rebase https://github.com/selendroid/selendroid.git
=> Rebase on upstream

lib/driver.js, lib/server.js, lib/uiautomator2.js, package.json
Code Refacorted and added adbkit to run JUnit instrumented test using 'adbKit'
=> Code Refacorted and added adbkit

lib/android-helpers.js, lib/commands/element.js, lib/commands/general.js, lib/commands/index.js, lib/commands/touch.js, lib/driver.js, lib/uiautomator2.js, package.json
- Implemented by taking the reference from [appium-android-driver](https://github.com/appium/appium-android-driver/blob/master/lib/commands/touch.js) module implementation
- MultiPointerGesture Handler(`/touch/multi/perform`) which will be invoked from [`performMultiAction`](https://github.com/sravanmedarapu/appium-uiautomator2-driver/blob/2791e11e5a0aa22c4fda3ac3c9bfff7aed71133f/lib/commands/touch.js#L120),  implemented in UiAutomator2-server module - [#8](https://github.com/appium/appium-uiautomator2-server/pull/8)
=> Added MultiTouch Functionality

lib/android-helpers.js, lib/commands/element.js, lib/commands/general.js, lib/commands/touch.js, lib/driver.js, package.json
Integration of Touch actions(Touch up ,touch move and touch down) and AppStrings handlers with driver
=> Touch actions and app strings driver changes

lib/commands/actions.js, test/functional/commands/touch/swipe-e2e-specs.js
Added swipe action in the driver module and integrated with server module.Added specs for swipe.
=> Added swipe action and integrated with server module with specs

lib/driver.js, package.json
- Updated params to invoke [`installApkRemotely `](https://github.com/appium/appium-android-driver/blob/master/lib/android-helpers.js#L255) as per the changes in [appium-android-driver](https://github.com/appium/appium-android-driver/commit/91620e880eb5d91e86465b0a56343be66b14780e#diff-f64f06d264dffd32eb8d87f1b3095989R236)
=> Updated driver.js as per appium-android-driver modifications

lib/commands/actions.js, lib/commands/index.js
Changes in this PR are with respective to the changes  [here.](https://github.com/appium/appium-android-driver/pull/173) Removed redundant code.
=> Updated swipe method to use the android-driver swipeOpts

.gitignore, bin/install.js, lib/driver.js, lib/installer.js, lib/uiautomator2.js, package.json
- Refactored driver.js to `checkAppPresent` only on `app` cabability
- Downloading UiAutomator2 server apks while installing driver module
=> Refactored - download server apks while installing module and capabilites handling

lib/driver.js, lib/installer.js, lib/uiautomator2.js
- Refactored server apks path as per the new changes. 
- Adding `appPackage` in capability on the absence.
=> Refactored

.travis.yml, lib/commands/actions.js, lib/commands/element.js, lib/commands/general.js, lib/driver.js, package.json, test/functional/commands/attribute-e2e-specs.js, test/functional/commands/file-movement-e2e-specs.js, test/functional/commands/find/by-accessibility-id-e2e-specs.js, test/functional/commands/find/by-id-e2e-specs.js, test/functional/commands/find/by-uiautomator-e2e-specs.js, test/functional/commands/find/by-xpath-e2e-specs.js, test/functional/commands/find/find-basic-e2e-specs.js, test/functional/commands/find/from-el-e2e-specs.js, test/functional/commands/find/invalid-strategy-e2e-specs.js, test/functional/commands/general-e2e-specs.js, test/functional/commands/geo-location-e2e-specs.js, test/functional/commands/ime-e2e-specs.js, test/functional/commands/keyboard-e2e-specs.js, test/functional/commands/orientation-e2e-specs.js, test/functional/commands/source-e2e-specs.js, test/functional/commands/touch/swipe-e2e-specs.js, test/functional/commands/url-e2e-specs.js
-  Updated NO_PROXY list and capabilities for the current session metadata
- Added attribute and Orientation related actions
- Added specs
=> Added Oreientation, Attribute related actions and specs

lib/driver.js, lib/installer.js, package.json
depends on #https://github.com/appium/appium-uiautomator2-server/pull/26
=> Changed device port number

lib/commands/general.js, lib/driver.js, lib/uiautomator2.js
- Added check point for installing server apks based on server versionName
- Updated NO_PROXY list 
- added getWindowSize
=> Added check point for installing server apks based on server versionName

lib/installer.js, test/functional/commands/find/by-xpath-e2e-specs.js
=> Added spec for TOAST message verification

lib/driver.js, package.json
- Ignore if removePortForward throws error
- Call to grant permissions
https://github.com/appium/appium-adb/pull/189
@imurchie and @jlipps
=> Grant permissions and ignore exception from removePortForward

lib/commands/index.js, lib/commands/network.js, lib/installer.js, test/functional/commands/network-e2e-specs.js
depends on 
- #https://github.com/appium/appium-uiautomator2-server/pull/42
- #https://github.com/appium/appium-android-driver/pull/196
Fix for appium/appium#6615
cc: @jlipps, @imurchie
=> Added setWifiState

lib/commands/element.js
This is related to PR: https://github.com/appium/appium-uiautomator2-server/pull/48
=> Making change in driver to pass element instead of elementId in command payload

lib/driver.js, lib/installer.js
FIX #https://github.com/appium/appium/issues/7654
=> Updated NO_PROXY to include /log

lib/driver.js, package.json, test/functional/driver-e2e-specs.js
Depends on #https://github.com/appium/appium-adb/pull/195
Req Ticket: #https://github.com/appium/appium/issues/3210
cc: @jlipps, @imurchie
=> added device screen size, model and manufacturer details to session

lib/driver.js, package.json
I made a fix to the call to the unlock method since we change it on `appium-android-driver`. 
Please review @jlipps @imurchie
=> update call to appium-android-driver params

lib/driver.js
Issue #https://github.com/appium/appium/issues/7984
=> added is_keyboard_shown to NO_PROXY list

lib/commands/network.js, lib/driver.js, test/unit/commands/network-specs.js
Addresses https://github.com/appium/appium/issues/8267
=> Fix network state change for uiautomator2 driver

lib/driver.js
Fixes https://github.com/appium/appium/issues/8272
=> Define grantPermissions method to uiautomation2 driver

lib/desired-caps.js, lib/uiautomator2.js
Sometimes things are slow and the server does not start responding fast enough. 
See https://travis-ci.org/appium/appium-uiautomator2-driver/jobs/228376321#L3195-L3227
=> Make the timeout for the server to come up be configurable

lib/commands/element.js
Please merge it after https://github.com/appium/appium-uiautomator2-server/pull/56 is merged and published
=> Update getAttribute logic for boolean attributes

lib/commands/element.js, lib/driver.js
Addresses https://github.com/appium/appium/issues/8644
=> Fix getting element's tag name

lib/driver.js, lib/uiautomator2.js, package.json, test/functional/commands/attribute-e2e-specs.js, test/functional/driver-e2e-specs.js
Pass adb port into `adbkit`.
Experimented with removing `adbkit` dependency but still got `IllegalStateExceptions`. 
Cc: @aluedeke
=> Allow adb port to be changed

.travis.yml, bin/install.js, lib/driver.js, package.json, test/functional/commands/attribute-e2e-specs.js, test/functional/commands/element-e2e-specs.js, test/functional/commands/file-movement-e2e-specs.js, test/functional/commands/find/by-accessibility-id-e2e-specs.js, test/functional/commands/find/by-id-e2e-specs.js, test/functional/commands/find/by-uiautomator-e2e-specs.js, test/functional/commands/find/by-xpath-e2e-specs.js, test/functional/commands/find/find-basic-e2e-specs.js, test/functional/commands/find/from-el-e2e-specs.js, test/functional/commands/find/invalid-strategy-e2e-specs.js, test/functional/commands/general-e2e-specs.js, test/functional/commands/geo-location-e2e-specs.js, test/functional/commands/ime-e2e-specs.js, test/functional/commands/keyboard-e2e-specs.js, test/functional/commands/network-e2e-specs.js, test/functional/commands/orientation-e2e-specs.js, test/functional/commands/source-e2e-specs.js, test/functional/commands/touch/multi-action-e2e-specs.js, test/functional/commands/touch/swipe-e2e-specs.js, test/functional/commands/url-e2e-specs.js, test/functional/desired.js, test/functional/driver-e2e-specs.js
* Run functional tests on Travis
* Fixed broken tests by waiting for elements to exist before operating on them
=> Travis fixes

lib/driver.js, test/functional/commands/find/find-system-ui-el-e2e-specs.js
Fix for https://github.com/appium/appium-uiautomator2-server/issues/61
=> Add allowInvisibleElements

package.json, test/functional/commands/keyboard/keyboard-e2e-specs.js
Establish that https://github.com/appium/appium/issues/8279 is no longer a problem.
=> Add test of typing into field with maxLength set

package.json
Address install [issue](https://github.com/appium/appium-uiautomator2-server/pull/66#issuecomment-317017483)
=> Moved appium-gulp-plugins from devDependencies to dependencies section

lib/commands/actions.js, lib/driver.js
Addresses https://github.com/appium/appium/issues/8951
=> Add handlers for press_keycode and long_press_keycode endpoints

.travis.yml, package.json, test/functional/commands/keyboard/keyboard-e2e-specs.js
Direct port of `appium-android-driver` tests for key event functionality, to complete https://github.com/appium/appium-uiautomator2-driver/pull/85
=> Port over android driver key event tests

lib/driver.js, lib/installer.js, test/functional/commands/url-e2e-specs.js, test/unit/driver-specs.js, test/unit/installer-specs.js
Adds functionality currently available in android driver.
Fixes https://github.com/appium/appium/issues/8906
=> Enable nativeWebScreenshot

lib/uiautomator2.js
Make the output cleaner for issues like https://github.com/appium/appium/issues/8956
=> Refactor server presence verification

index.js
Keep parity with appium server flag.
=> Add address flag

.travis.yml, lib/driver.js, package.json, test/functional/commands/context-e2e-specs.js, test/functional/commands/url-e2e-specs.js
Just to demonstrate that it works. These _will_ fail on Android O. See https://github.com/appium/appium/issues/8958
=> Add tests for context switching

package-lock.json, package.json, test/functional/commands/context-e2e-specs.js
The test as it was only made sure that the webview pid didn't map to "undefined", but didn't catch mis-parsing of the name in other ways. So make sure that we actually get the name we expect.
=> Fix context test

lib/driver.js, test/functional/commands/orientation-e2e-specs.js
Make `orientation`  capability work. Resolves https://github.com/appium/appium/issues/9391
=> Fix initial orientation setting

lib/driver.js
Recording-related commands should be managed with adb commands.(no-proxy)
=> add recording related commands in no proxy

.travis.yml, package.json, test/functional/commands/language-e2e-specs.js, test/functional/commands/strings-e2e-specs.js
ref: https://github.com/appium/appium-android-driver/pull/287
After merging ^ and publishing the new version, I'll update `"appium-android-driver": "^1.27.1",` in `package.json`.
=> Fix setting locale code

lib/driver.js, package.json, test/functional/driver-e2e-specs.js
This also updates to lodash 4, as I was having issues with conflicts with other appium packages.
=> Add deviceScreenDensity to session caps

lib/commands/element.js, lib/driver.js
Based on https://github.com/appium/appium-uiautomator2-server/pull/102
=> Add element screenshot endpoint handler

lib/commands/general.js
Addresses opening scheme links with UIA2. See https://github.com/appium/java-client/issues/787 for more details
=> Add handler for setUrl command in native context

test/functional/driver-e2e-specs.js
Recent change (https://github.com/appium/appium-base-driver/commit/9f95a75d9660c39b6f2a92689a19252b49263795) have made this test fail.
=> Fix test for apk non-existence

lib/commands/element.js
Addresses https://github.com/appium/appium/issues/9969
=> Fix element tap with coordinates

lib/driver.js
Data can be wiped from the user side via avdAgs capability.
=> Don't force `wipe-data`, if the `reboot` capability is provided.

lib/commands/index.js, lib/commands/screenshot.js, test/unit/driver-specs.js
Based on https://github.com/appium/appium-uiautomator2-server/pull/112
=> Replace custom /screenshot implementation with the native one

lib/driver.js, lib/uiautomator2.js, package.json, test/functional/driver-e2e-specs.js, test/unit/commands/touch-specs.js
=> Update the codebase to support appium-adb module v. 6.0.1

lib/driver.js
Based on https://github.com/appium/appium-base-driver/pull/185
=> Add POST /app_state to NO_PROXY list

.gitignore, lib/driver.js
expose the accessibility scroll data from https://github.com/appium/appium-uiautomator2-server/pull/119 (though this can be merged in advance of that one, doesn't matter)
=> get session details from the uiauto2 server now that it has them

lib/uiautomator2.js
The previous implementation mostly duplicates what is already present in `adb.installOrUpgrade` method
=> Optimise server apk install for UIA2 server

lib/driver.js, package.json, test/functional/commands/strings-e2e-specs.js
* The change in https://github.com/appium/appium-uiautomator2-driver/commit/3e7a2e1afc2df14b4546d7853257b9f66c50af78 has changed the output of `getStrings`
* Update the tests to be the new output
=> Fix strings test

lib/commands/general.js, lib/driver.js
Bases on https://github.com/appium/appium-base-driver/pull/199 and https://github.com/appium/appium-uiautomator2-server/pull/124
=> Add clipboard handlers

lib/commands/general.js, lib/driver.js, lib/server.js, package.json
This just imports what was implemented for android-driver in https://github.com/appium/appium-android-driver/pull/343
=> Import logs broadcast via websocket feature

lib/driver.js, test/functional/commands/general/network-e2e-specs.js, test/functional/commands/geo-location-e2e-specs.js
Copy-paste from Appium Android Driver commit
=> Add otherApps cap

lib/commands/general.js
Reverts appium/appium-uiautomator2-driver#158
=> Revert "Fix get/post settings"

lib/commands/alert.js, lib/commands/general.js, lib/commands/index.js, lib/driver.js, package.json
Based on https://github.com/appium/appium-uiautomator2-server/pull/147
=> Add alert commands

lib/driver.js, test/functional/driver-e2e-specs.js
It is sometimes quite useful to have the API level available.
=> Add API level to device caps

lib/commands/actions.js
This is to support https://github.com/appium/appium-uiautomator2-server/pull/157
=> Add flags argument to pressKeyCode

lib/driver.js
This might address https://github.com/appium/appium/issues/10749
=> Force kill uiautomator process before server startup

.travis.yml, lib/commands/general.js, lib/commands/viewport.js, lib/driver.js, test/functional/commands/keyboard/keyboard-e2e-specs.js, test/functional/helpers/session.js
A few tweaks to make things run smoother.
=> Stabilize the build

.travis.yml, lib/commands/screenshot.js, lib/desired-caps.js, lib/driver.js, package.json, test/functional/commands/general/screenshot-e2e-specs.js
Implementation for the uiautomator2 driver of https://github.com/appium/appium-base-driver/pull/230, which this depends on.
=> support mjpeg stream screenshot via new mjpegScreenshotUrl cap

lib/uiautomator2.js
The previous implementation was messy and was hard to read
=> Refactor server components signing verification

lib/commands/general.js
Based on https://github.com/appium/appium-uiautomator2-server/pull/186
=> Add a mobile: endpoint for retrieving the device information

lib/commands/general.js
This PR depends on https://github.com/appium/appium-android-driver/pull/428 and will be available as soon as android driver is published
=> Add editor action mobile command

.travis.yml, lib/driver.js, package.json
The PR depends on https://github.com/appium/appium-uiautomator2-server/pull/191
=> Use /info endpoint to add device information to caps instead of slow adb calls

lib/commands/general.js, lib/driver.js, test/functional/commands/general/attribute-e2e-specs.js
Addresses https://github.com/appium/appium/issues/11627
=> Fix timeouts call

lib/commands/element.js, lib/driver.js
Partially addresses https://github.com/appium/appium/issues/11619
=> Patch getRect call for chromedriver in JSONWP mode

lib/driver.js, package.json, test/unit/driver-specs.js
addressed in https://github.com/appium/appium-android-driver/pull/461#issuecomment-435773760
=> add set hiddne api policy

.travis.yml, package.json, test/functional/commands/general/ime-e2e-specs.js, test/functional/commands/keyboard/keyboard-e2e-specs.js
Still some flakiness with this, but it's much better on Travis.
=> Another try at deflaking the keyboard tests

test/functional/commands/keyboard/keyboard-e2e-specs.js, test/functional/desired.js
=> Fix the build

lib/uiautomator2.js, package.json
This change should improve driver startup performance and fix packages upgrade logic upon driver update
=> Update server packages upgrade logic

.travis.yml, lib/uiautomator2.js, package.json, test/functional/commands/find/find-basic-e2e-specs.js, test/functional/commands/find/from-el-e2e-specs.js
The server has been migrated to androidx
=> Update the driver to support uia2 server v3

test/functional/desired.js
Fix some flakiness in the build.
=> Bump adb exec timeout on Travis

lib/uiautomator2.js
Addresses https://github.com/appium/appium/issues/12019
=> Fix possibile race condition on instruments startup

lib/driver.js
Related to https://github.com/appium/appium-android-driver/pull/491
=> Remove the redundant java version retrieval

lib/uiautomator2.js, package.json
depends on https://github.com/appium/appium-adb/pull/416
=> add timeoutcapname as uiautomator2ServerInstallTimeout to notify users about it

lib/driver.js, lib/uiautomator2.js, package.json
https://github.com/appium/appium-android-driver/pull/502 for UIA2
TODO: update android-driver version
=> add uninstallOtherPackages

.travis.yml, test/functional/helpers/session.js
Update Travis config, and add an alert id to the check for system alerts on session startup.
=> Fix Travis build

lib/driver.js
this is required to support https://github.com/appium/appium-base-driver/pull/328
=> add execute driver to no-proxy list

lib/uiautomator2.js
This should help to avoid the state described in https://github.com/appium/appium/issues/13144
=> fix: Enable replace option for server packages install

lib/driver.js
Fixes https://github.com/appium/appium/issues/13471
=> fix: change errant uiautomation2 reference

lib/driver.js
See https://github.com/appium/appium/issues/13509 for more details
=> fix: Prefer IPv4 address to the host name

lib/uiautomator2.js, package.json
This should speed up the communication between the driver and the server
=> feat: Enable keepAlive mode for proxied requests

lib/commands/general.js, lib/driver.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/586
=> feat: Add mobile commands to start/stop screen streaming

lib/commands/general.js, package.json
https://github.com/appium/appium-android-driver/pull/598
=> feat: Add mobile: API to retrieve notifications

lib/desired-caps.js, lib/driver.js
Addresses https://github.com/appium/appium/issues/13782
=> feat: Consider userProfile when starting the app under test

lib/driver.js
https://github.com/appium/appium/issues/13989
=> feat: make 'mobile:' commands available in web context

lib/driver.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/610
=> chore: Update isEmulator detection

lib/driver.js, package.json
https://github.com/appium/appium-android-driver/pull/614 for uia2.
Need to update appium-android-driver after the PR publishment.
=> feat: add ignoreHiddenApiPolicyError

package.json, test/functional/commands/find/by-uiautomator-e2e-specs.js
Addresses https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=8754&view=logs&j=66f1e43a-163e-5d1c-9c47-72628325f4ea&t=60447e9b-2dbf-521f-937b-5146b289cd42
=> chore: Bump uia2 server version

.gitignore, lib/commands/general.js, test/unit/commands/general-specs.js
Running a few tests locally
Addressing https://github.com/appium/appium/issues/14116
=> feat: include sensorSet to mobile commands

lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/623
=> feat: Add mobile endpoint for getDeviceTime

lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/630
=> feat: Add support for mobile helper related to emulator console commands execution

lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/634
=> feat: Add 'mobile: deleteFile' endpoint

lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/647
=> feat: Add mobile helpers to start/stop services

lib/commands/general.js
https://github.com/appium/appium/issues/14418#issuecomment-639827095
=> fix: Fix the endpoint for mobile:scroll call

lib/driver.js
https://github.com/appium/appium/issues/14753
=> chore: Avoid using the lock if systemPort is set in capabilities

lib/commands/general.js, package.json
Related to appium/appium#14745
=> feat: "mobile: getContexts" on Android

lib/commands/general.js, lib/commands/gestures.js, lib/commands/index.js, package.json
Based on https://github.com/appium/appium-uiautomator2-server/pull/382
=> feat: Add mobile endpoints for gesture shortcuts

lib/driver.js, package.json
Based on https://github.com/appium/appium-adb/pull/557
=> feat: Add server packages to Doze whitelist

README.md
I want to update README, so it contains all the necessary info that helps one to use the driver effectively. This will be the first step
=> docs: Document UiAutomator2 capabiltties

README.md, lib/desired-caps.js, lib/driver.js, lib/uiautomator2.js
https://github.com/appium/appium/issues/14998
=> feat: Add a possibility to configure the server read timeout

README.md, lib/commands/general.js, lib/commands/gestures.js, package.json
Based on https://github.com/appium/appium-uiautomator2-server/pull/415/
=> feat: Add doubleClick mobile geature

lib/css-converter.js
Fixes https://github.com/appium/appium/issues/15269
=> fix: Update ID locator formatting logic for CSS parsing

lib/uiautomator2.js
https://github.com/appium/appium/issues/15274
It is reasonable to disable this to prevent unexpected fatal error.
=> feat: set 'disableAnalytics true'

lib/driver.js
Related to https://github.com/appium/appium/issues/15367#issuecomment-841140265
=> feat: Validate system port state before opening a new session

lib/commands/element.js, package.json, test/functional/commands/general/element-e2e-specs.js
Add support to retrieve active element from android application.
Corresponding PR.
https://github.com/appium/appium-uiautomator2-server/pull/423
=> feat: Add active element support

lib/commands/gestures.js
Addresses https://github.com/appium/appium/issues/15392
=> fix: Pass origin parameter properly to `'/touch/scroll'` API

README.md, package.json
Should be merged after https://github.com/appium/appium-android-driver/pull/699 is merged
https://github.com/appium/appium-android-driver/pull/699/files#r655874047
=> docs: make enableWebviewDetailsCollection true by default

README.md, lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/701
Related to https://github.com/appium/appium/issues/15620
=> feat: Add support for startActivity extension

README.md, lib/commands/general.js, package.json
https://github.com/appium/appium-android-driver/pull/707
=> feat: Add support of `mobile: clearApp` extension

README.md, lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/709
=> feat: Add `mobile: unlock` extension

lib/commands/general.js, package.json
https://github.com/appium/appium/issues/15929
=> refactor: Fetch display density value from UIA2 server rather than from adb

lib/driver.js
for https://github.com/appium/appium/issues/16106 as UIA2
Will do the same change in the espresso driver later.
=> feat: add se log route as no-proxy

lib/commands/find.js, lib/css-converter.js, test/unit/css-converter-specs.js
Related to https://github.com/appium/java-client/issues/1621
=> fix: Respect the default app package while building android locators from css ones

README.md, lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/721
=> feat: Add an extension for GPS cache refresh

README.md
expected result will be uia2 2.0.3 will be released
=> fix: dummy PR to test the release action

README.md
https://github.com/appium/appium-android-driver/issues/738
=> docs: address autoritate by monkey in readme

README.md
It would be helpful to address which is `script` part for https://github.com/appium/appium/issues/17171#issuecomment-1179763016
=> docs: update readme about script in the app localization

package.json, scripts/reset.js
https://github.com/appium/appium-uiautomator2-driver/issues/542
=> feat: Add reset script

docs/activity-startup.md
no much info about this exception in the internet, so it might be helpful to have
=> docs: add noSign is necessary case as the troubleshooting

README.md, package.json
Based on https://github.com/appium/appium-android-driver/pull/774
=> feat: Add support of updated changePermissions args

.github/workflows/functional-test.yml, package.json, test/functional/commands/general/attribute-e2e-specs.js, test/functional/commands/general/context-e2e-specs.js, test/functional/commands/general/element-e2e-specs.js, test/functional/commands/general/general-e2e-specs.js, test/functional/commands/general/ime-e2e-specs.js, test/functional/commands/general/mobile-command-e2e-specs.js, test/functional/commands/general/network-e2e-specs.js, test/functional/commands/general/source-e2e-specs.js, test/functional/commands/general/url-e2e-specs.js, test/functional/desired.js
A part of https://github.com/appium/appium/issues/16402
This PR enables specs under `test/functional/commands/general` directory on CI
=> ci: fix commands/general specs

README.md, lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/791
=> feat: Add setConnectivity and getConnectivity extensions

README.md, lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/801
=> feat: Add mobile extensions for on-screen keyboard

README.md, lib/commands/general.js, package.json
Based on https://github.com/appium/appium-android-driver/pull/812
=> feat: Add a wrapper over status bar commands

lib/commands/touch.js, lib/driver.js
Addresses https://github.com/appium/appium-uiautomator2-driver/issues/624
=> fix: make releaseActions to a no-op

README.md, lib/commands/general.js, lib/commands/screenshot.js
Similar to https://github.com/appium/appium-mac2-driver#macos-screenshots
=> feat: Allow to take screenshots of multiple Android displays

README.md, lib/execute-method-map.ts, package.json
https://github.com/appium/appium/issues/18965
=> feat: Add 'mobile: deviceidle' extension

lib/driver.ts, lib/types.ts, test/unit/driver-specs.js
Got rid of opts.reboot and also optimized/made faster the fetching of device info
=> chore: Remove obsolete driver options

lib/driver.ts
fixes https://github.com/appium/appium-uiautomator2-driver/issues/687
=> fix: Properly read systemPort value from capabilities

README.md, lib/execute-method-map.ts, package.json
Based on https://github.com/appium/appium-android-driver/pull/884
=> feat: Add support of UiModeManager service commands

.github/workflows/functional-test.yml, .github/workflows/unit-test.yml
See https://github.com/appium/appium-xcuitest-driver/pull/2224
=> ci: run CI only for master branch

package.json
https://github.com/appium/appium-uiautomator2-server/pull/582
=> feat: bump server's targetSdkVersion from 30 to 32

package.json
lets release with minor fixes before the major version update of the server.
I'll merge tomorrow (after ci will be green)
=> fix: minor fixes for upcoming androidx.test.uiautomator:uiautomator:2.3.0

package.json
The new server version contains uiautomator 2.3.0-beta01
=> feat: Bump the server version

package.json
to apply https://github.com/appium/appium-android-driver/pull/895
I'll merge once the CI passes
=> fix: io.appium.settings process check as the foreground service check

lib/commands/general.js, lib/driver.ts, package.json
Similar to https://github.com/appium/appium-android-driver/pull/897/
=> feat: Use APIs imported from the io.appium.settings package

package.json
https://github.com/appium/appium-android-driver/pull/908
For https://github.com/appium/appium/issues/19713
=> fix: createADB

lib/driver.ts, package.json
Most of adb commands that we run can be executed in parallel
=> feat: Paralellize session setup steps

lib/driver.ts, test/unit/driver-specs.js
Related to https://github.com/appium/appium-android-driver/pull/913#discussion_r1478890572
=> fix: Detect the browser activity dynamically

lib/driver.ts, test/unit/driver-specs.js
fixes https://discuss.appium.io/t/i-cant-get-any-command-working-on-android-chrome-browser/41586/3
=> fix: Init adb as the first step upon session creation

README.md
I saw an opportunity to contribute and I took it!
=> README: Fixed a typo

docs/android-mobile-gestures.md
The percent value should less than or equal to 1
=> docs: Update percent value for scroll gesture

.github/workflows/functional-test.yml, .github/workflows/unit-test.yml
Same as https://github.com/appium/appium/pull/20059.
Also adjusted unit tests to be skipped for Markdown file changes.
=> ci: use GH Action for detecting LTS Node

README.md, lib/execute-method-map.ts, package.json
Based on https://github.com/appium/appium-android-driver/pull/931
=> feat: Add `mobile: injectEmulatorCameraImage` extension

.github/workflows/functional-test.yml
I'll merge once the func test ci passes
=> ci: fix typo and teak a bit

README.md, lib/execute-method-map.ts, package.json
https://github.com/appium/appium-android-driver/pull/932
=> feat: add user option for mobile: isAppInstalled

lib/commands/execute.js
Missed in the re-mapping refactor.
-> closes https://github.com/appium/appium-uiautomator2-driver/issues/782
=> fix: mobileBackgroundApp

README.md
Perhaps it would be nice to address chrome custom tabs thing as a troubleshooting
https://github.com/appium/appium/issues/16031
=> docs: address chrome custom tabs

docs/capability-sets.md
Similar to https://github.com/appium/appium-xcuitest-driver/pull/2408
=> docs: Describe capability sets for common testing scenarios

docs/android-mobile-gestures.md
Add python example for swipeGesture
=> docs: Add python example for swipeGesture

docs/android-mobile-gestures.md
Add Javascript examples for two different Gestures since there are no code examples for JS
=> docs: Add Javascript examples for clickGesture and flingGesture

test/functional/commands/general/source-e2e-specs.js
This will also close https://github.com/appium/appium-uiautomator2-driver/security/advisories/GHSA-w2h6-7p4g-2r23
=> test: update parseFromString usage

.github/workflows/functional-test.yml, README.md, package.json
This disables automatic chromedriver download upon module installation
=> feat: Bump appium-chromedriver

README.md, package.json
Based on https://github.com/appium/appium-android-driver/pull/961
=> docs: Document mobile geolocation apis

README.md
just a minor modification:
Maybe it would be better indentation of this topic with `##` instead of `#` to fit for other items
=> docs: add # to arrange the indentation

package.json
=> chore: bump adb to include supporting activities with unicode chars

package.json
Supports https://github.com/appium/appium-uiautomator2-driver/issues/859
=> feat: bump appium-adb to handle screenState=SCREEN_STATE_OFF as locked

lib/driver.ts, lib/uiautomator2.js
Related to https://github.com/appium/appium/pull/21021
We won't need a workaround with this parameter being present
=> fix: Add base path to proxy options

lib/method-map.ts
=> chore: add deprecated: true for get clipboard

package.json
=> chore: bump appium-android-driver to 11.0.4
